services:
  postgres:
    build: ./internal/fixtures/postgres
    privileged: true
    hostname: postgres
    environment:
      DB_READ_HOST: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: ./internal/figures/postgres/tables.sql
        target: /tmp/psql_data/tables.sql